services:
  - type: web
    name: legal-backend
    env: python
    plan: free
    buildCommand: |
      export PYTHON_VERSION=3.10.12
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
